### ISSUE TITLE
Review Ticket Week 3

### ISSUE THREAD

**Issue by connorw72** [connorw72/food#40]
Scrum Master and Technical Officer

- [ ] [PBL Highlights](https://github.com/connorw72/food/tree/main/blueprints)
- [ ] [Video](https://watch.screencastify.com/v/r9C9LbUWQlCFxn9QgZpz)

Design Manager tangibles

- [ ] Layout. <source link>
- [ ] [Front End Feature Screen](https://github.com/connorw72/food/blob/main/templates/dogs.html)
- [ ] [Front End Screen 2](https://github.com/connorw72/food/blob/main/templates/birds.html)
- [ ] Front End Screen 3: <runtime link>

Scrum Master tangibles

- [ ] [GitHub Scrum Board](https://github.com/connorw72/food/projects/1#column-16866244)
- [ ] [Scrum Board](https://github.com/connorw72/food/projects/1#column-17077693)

Technical officer tangibles

Database with CRUD:

- [ ] [Runtime](https://github.com/connorw72/food/blob/main/crud/__init__.py)
- [ ] [View](https://github.com/connorw72/food/tree/main/crud/templates/crud)
- [ ] [Model](https://github.com/connorw72/food/blob/main/crud/model.py)

Deployment manager tangibles

- [ ] [Update procedure](https://github.com/connorw72/food/wiki/Deployment-Guide#process-to-perform-an-update)
- [ ] [Nginx config](https://github.com/connorw72/food/wiki/Deployment-Guide#process-to-perform-an-update)
- [ ] [Service config](https://github.com/connorw72/food/wiki/Deployment-Guide#process-to-perform-an-update)

GitHub admin tangibles

- [ ] Commit, pull request procedure <link to deployment guide that shows process>
- [ ] Branching procedure <link to deployment guide that show process to create and merge a branch>

Individual

- [ ] AP MCQ Test and Corrections [Tanay and Connor](https://docs.google.com/document/d/1yMnRk0cY8TWYl3YKTgz0OKkrI5Gac4pEyoyiffEeUoE/edit?usp=sharing), [Chase, Pranav, Colin](https://docs.google.com/document/d/1iU4SOdLDTyFTuoI4yuBxjvRjvVHq53I5JZgaCRP8Ah4/edit?usp=sharing)

**Comment by TANAY101405** [comment]
Tanay: 7.75/8  (I finished my deployment manager role but I could have added more PBL features since it was a PBL week; maybe worked on the bootstrap pages or work with SCSS)

**Comment by connorw72** [comment]
Connor - Scrum Master - Individual Grade 
7.65/8
Completed all scrum master requirements for the week with the expected backlog, readme, and with the ready to review. I did work on the project with the blueprints for each person so that the main.py is not clogged. However, I did not do much in terms of technicals, and will do that going forward. I completed the AP MCQ.

**Comment by ChaseOtt** [comment]
Chase: 7.5/8 I did my job as Github Admin by making sure the branches ran smoothly however I could have done more things with PBL. I also did all of my quizzes for the week.

**Comment by KoolKidKai** [comment]
**Colin - Technical Officer 8/8**
My job was to create the CRUD features and put them into the website.
The SQL CRUD and search bar are both properly integrated into the website
I also finished the AP MCQ along with all corrections.

**Comment by TANAY101405** [comment]
Pranav Parthasarathy (Design Manager) - 7.75/8
Job was the design manager and worked on 2 out of the 3 html pages with the frontend code. The layout was not finished and the rest of the group could have learned a bit more about SCSS. Completed the mcq with test corrections.
